### ISSUE TITLE
오타발견

### ISSUE THREAD

**Issue by rinechran** [HIPERCUBE/64bit-Multicore-OS#2]
https://github.com/HIPERCUBE/64bit-Multicore-OS/blob/master/book/Ch3_64%EB%B9%84%ED%8A%B8%20%ED%94%84%EB%A1%9C%EC%84%B8%EC%84%9C%EC%9D%98%20%EC%9D%B4%EB%AA%A8%EC%A0%80%EB%AA%A8.md  페이지에 
 "ㅓㅂㅁ용" 이라는  오타 발견

**Comment by HIPERCUBE** [comment]
오타 제보 감사합니다 :D
